receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:

  otlphttp:
    endpoint: "http://refinery:8080"
    tls:
      insecure: true
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}" 

service:
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]